### ISSUE TITLE
Support React 0.14.0

### ISSUE THREAD

**Issue by mgreer** [mzabriskie/react-disqus-thread#11]
Currently blocking install in package.json. Since RC1 was just released, would be good to have a roadmap.

Happy to do a PR.

**Comment by adriantoine** [comment]
@mzabriskie React 0.14 stable has been released now, `package.json` should be updated.

**Comment by crubier** [comment]
+ 1 :-)

**Comment by mzabriskie** [comment]
Just released 0.3.0 which supports react@0.14.0
