### ISSUE TITLE
react 15 released, please upgrade too

### ISSUE THREAD

**Issue by lyquocnam** [mzabriskie/react-disqus-thread#21]

**Comment by zallek** [comment]
:+1:

**Comment by eisenbergrobin** [comment]
PR Submitted: https://github.com/mzabriskie/react-disqus-thread/pull/24

**Comment by sugarshin** [comment]
plz publish to npm.

**Comment by zallek** [comment]
+1

**Comment by eisenbergrobin** [comment]
Until then, setting "git://github.com/mzabriskie/react-disqus-thread#0644121240d73c129f140f58e558fd4eae653fb1" as a dep in your `package.json` works.

**Comment by sugarshin** [comment]
I know. not a fundamental solution. @mzabriskie plz publish 🙏

**Comment by mzabriskie** [comment]
Released `0.4.0` with `react@15` support

**Comment by zallek** [comment]
Thx

Envoyé depuis mon nexus 5
Le 31 mai 2016 5:57 PM, "Matt Zabriskie" notifications@github.com a
écrit :

**Comment by sugarshin** [comment]
@mzabriskie Thx !
