### ISSUE TITLE
Can't require in node

### ISSUE THREAD

**Issue by cesarandreu** [mzabriskie/react-disqus-thread#4]
When I try to require react-disqus-thread it gives me an error because of the jsx syntax. For now I'm using the build version.

Would it be reasonable to give `lib/disqus-thread.js` a jsx extension so loaders can properly compile and include it?

**Comment by mzabriskie** [comment]
Sorry it took so long, but I have removed JSX altogether.

**Comment by cesarandreu** [comment]
Great :D
